/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unikomKsi.PolyAndCaesar;

import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.Toolkit;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import unikomKsi.PolyAndCaesar.view.Caesar;
import unikomKsi.PolyAndCaesar.view.Polyalphabetic_key;
import unikomKsi.PolyAndCaesar.view.Polyalphabetic_normal;

/**
 *
 * @author yudha
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    
    public home() {
//        this.setUndecorated(true);
        //this.setAlwaysOnTop(true);
        this.setResizable(false);
        initComponents();      
    }
    
    protected void tema(){
        try{
            UIManager.setLookAndFeel(new WindowsLookAndFeel());
        }catch(UnsupportedLookAndFeelException ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaAnggota = new javax.swing.JLabel();
        btn_poly_dinamis = new javax.swing.JButton();
        btn_caesar = new javax.swing.JButton();
        btn_poly = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaAnggota.setBackground(new java.awt.Color(255, 255, 255));
        namaAnggota.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        namaAnggota.setForeground(new java.awt.Color(255, 255, 255));
        namaAnggota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaAnggota.setText("NAMA ANGGOTA");
        getContentPane().add(namaAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 900, 50));

        btn_poly_dinamis.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_poly_dinamis.setForeground(new java.awt.Color(26, 188, 156));
        btn_poly_dinamis.setText("POLYALPHABETICAL");
        btn_poly_dinamis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_poly_dinamisMouseClicked(evt);
            }
        });
        btn_poly_dinamis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_poly_dinamisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_poly_dinamis, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 300, 50));

        btn_caesar.setBackground(new java.awt.Color(255, 255, 255));
        btn_caesar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_caesar.setForeground(new java.awt.Color(26, 188, 156));
        btn_caesar.setText("CAESAR");
        btn_caesar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_caesarMouseClicked(evt);
            }
        });
        btn_caesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caesarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_caesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 50));

        btn_poly.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_poly.setForeground(new java.awt.Color(26, 188, 156));
        btn_poly.setText("POLYALPHABETICAL DINAMIS");
        btn_poly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_polyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_poly, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 300, 50));

        jPanel1.setBackground(new java.awt.Color(26, 188, 156));
        jPanel1.setForeground(new java.awt.Color(26, 188, 156));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 900, 50));

        jPanel2.setBackground(new java.awt.Color(26, 188, 156));
        jPanel2.setForeground(new java.awt.Color(26, 188, 156));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unikomKsi/Image/10115532.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 240, 240));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unikomKsi/Image/10115496.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 240));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unikomKsi/Image/10115518.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 240, 240));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MOCH INDRA YUDHA L");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 200, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("10115496");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 200, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DANIYAL AHMAD R");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 200, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("10115518");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 200, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("10115532");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 200, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("IFFTIKHARUL UMMAH");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 200, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_poly_dinamisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_poly_dinamisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_poly_dinamisActionPerformed

    private void btn_caesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caesarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_caesarActionPerformed

    private void btn_polyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_polyActionPerformed
        // TODO add your handling code here:
        new Polyalphabetic_key().show();
    }//GEN-LAST:event_btn_polyActionPerformed

    private void btn_caesarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_caesarMouseClicked
        // TODO add your handling code here:
        new Caesar().show();
    }//GEN-LAST:event_btn_caesarMouseClicked

    private void btn_poly_dinamisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_poly_dinamisMouseClicked
        // TODO add your handling code here:
        new Polyalphabetic_normal().show();
    }//GEN-LAST:event_btn_poly_dinamisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      
        /* Create and display the form */
        home frame = new home();
        frame.tema();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_caesar;
    private javax.swing.JButton btn_poly;
    private javax.swing.JButton btn_poly_dinamis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel namaAnggota;
    // End of variables declaration//GEN-END:variables
}
